services:

  postgres:
    image: postgres:17.1-alpine3.20
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cr8s
    command: ["postgres", "-c", "log_statement=all"]

  redis:
    image: redis:7.4.1-alpine3.20


  app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/cr8s
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/